### ISSUE TITLE
Rename to comply with Spring Boot's naming guidelines

### ISSUE THREAD

**Issue by snicoll** [sasiperi/alexa-spring-boot#8]
The Spring Boot documentation [requests](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) that third-party starters be named `*-spring-boot-starter`. `alexa-spring-boot-starter` would, IMO, be a better name.

**Comment by sasiperi** [comment]
Did not realize that, thanks for sending me the link. 
I will change it to be alexa-spring-boot-starter instead. I will delete artifacts, but I am not sure if Sonatype folks will delete this from maven central completely and reindex so that it's not searchable, anything once released is somewhat permanent. I will request make a request with them anyway.

**Comment by snicoll** [comment]
Thanks for the quick reply. I doubt they will but I am not too worried about that as long as the project has the expected name going forward.

**Comment by sasiperi** [comment]
Changed the project name, now the latest artifact is been published as alexa-spring-boot-starter.
